language: node_js

node_js: 12

script:
  - npm run build
  - chmod 600 ./2019_1_SleeplessNights_id_rsa.pem
  - ssh-keyscan -H 89.208.198.186 >> ~/.ssh/known_hosts
  - scp -i ./2019_1_SleeplessNights_id_rsa.pem -r ./public/ ubuntu@89.208.198.186:/home/ubuntu/Deploy/Frontend
  -

branches:
  only:
    - Deploy

before_install:
  - openssl aes-256-cbc -K $encrypted_89440b23aba0_key -iv $encrypted_89440b23aba0_iv
    -in 2019_1_SleeplessNights_id_rsa.pem.enc -out ./2019_1_SleeplessNights_id_rsa.pem -d
